spring:
  cloud:
    vault:
      scheme: http
      host: ${VAULT_HOST:localhost}
      port: 8200
      token: ${VAULT_TOKEN}

  datasource:
    url: jdbc:oracle:thin:@//172.17.0.2:1521/orclpdb1
    username: oracletest
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
    schema: file:./schema.sql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        session_factory: org.hibernate.SessionFactory

server:
  port: 8005
