server:
  port: 8015

spring:
  datasource:
    url: jdbc:oracle:thin:@//172.17.0.2:1521/orclpdb1
    username: oracletest
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
    schema: file:./schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        session_factory: org.hibernate.SessionFactory

storage:
  type:GCS

# GCS Configuration
gcs:
  bucket-name: storage-box
  credentials:
    location: file:/home/dorustree/Documents/interstellar-403806-1874479b5980.json

