spring:
  datasource:
    url: jdbc:oracle:thin:@//172.17.0.2:1521/orclpdb1
    username: oracletest
    password: root123
    driver-class-name: oracle.jdbc.OracleDriver
    schema: file:./schema.sql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
        session_factory: org.hibernate.SessionFactory

server:
  port: ${SERVER_PORT:8007}

localsystementryBaseUrl: http://localhost
localgeneratorBaseUrl: http://localhost
livesystementryBaseUrl: http://gep-dev-system-entry.gep-dev-201902.svc.cluster.local
livegeneratorBaseUrl: http://gep-dev-generator.gep-dev-201902.svc.cluster.local
localname: development
